### PR TITLE
fixed ets busmonitor (ets4, ets5)

### PR DESCRIPTION
**Pull request by p3root**
I dont know why this code is as it is. I found out that pdu[1] is a number of additional bytes that follow. ETS4/ETS5 can't handle this in the busmonitor. 

The "int no" should be used otherwise. As referred here http://www.eb-systeme.de/?page_id=479 (5th: send a TUNNELLING_REQUEST)
The param "int no" should be in the "Connection Header" and not given as additional info in cEMI Frame.

### CODE REVIEW

**Comment by p3root** [comment]
Please feel free to discuss this with me, and explain me why this has been done so...

**Comment by timowi** [comment]
I have no documentation. I had a look at the calimero implementation.
The current one seems wrong.
Does the following work?

pdu.resize (p.pdu () + 5);
pdu[0] = code; // This is always 43 (0x2B)
pdu[1] = 3; // Size of additional header
pdu[2] = 3; // Type 3 = Status
pdu[3] = 1; // Length of above field
pdu[4] = no & 0x7; // Status field, bit 2:1 is sequence number
pdu.setpart (p.pdu, 5);

Seems like there was one bit too much. If calimero implementation is correct a timestamp have to be supplied too.

**Comment by p3root** [comment]
I'll give it a try tomorrow. I just found out that when you use the busmonitor with a normal usb knx gateway that there are 7 additional bytes. I had no time to analyse that in detail.
________________________________
Von: Timo<mailto:notifications@github.com>
Gesendet: ‎07.‎01.‎2015 22:13
An: Makki1/knxd<mailto:knxd@noreply.github.com>
Cc: Patrik Pfaffenbauer<mailto:patrik.pfaffenbauer@p3.co.at>
Betreff: Re: [knxd] fixed ets busmonitor (ets4, ets5) (#21)

I have no documentation. I had a look at the calimero implementation.
The current one seems wrong.
Does the following work?

pdu.resize (p.pdu () + 5);
pdu[0] = code; // This is always 43 (0x2B)
pdu[1] = 3; // Size of additional header
pdu[2] = 3; // Type 3 = Status
pdu[3] = 1; // Length of above field
pdu[4] = no & 0x7; // Status field, bit 2:1 is sequence number
pdu.setpart (p.pdu, 5);

Seems like there was one bit too much. If calimero implementation is correct a timestamp have to be supplied too.

---

**Comment by timowi** [comment]
That's what I found out from calimero sources.
Additional Header Format is

1 Byte Type
1 Byte Length
L Byte Data

The old code does not follow this...

Type 0x03 Status Info
Length 1 Byte
Bits 7:3 Status Flags, Bits 2:1 sequence number

Type 0x04 Timestamp
Length 2
Timestamp according to cEMI standard

Type 0x06 extended Timestamp
Length 4
extended Timestamp according to cEMI standard

My suggestion just sends the parameter "no" as sequence number in status byte (all flags 0). According calimero sources status and timestamp are mandatory. These are your 7 Byte. Status Flag and normal timestamp.

Can you try to figure out what the timestamp format is? I think it's somethink like a relative seconds or milliseconds counter. For the two byte variant seconds I think. Should be possible by comparing values in a wireshark trace.

**Comment by p3root** [comment]
Ok, the 7byte additional header works, but I can't figure out what kind of timestamp it is. I have 2 traces with the usb interface and timestamps from the busmonitor. But still no idea.

trace

**Comment by timowi** [comment]
> Maybe the timestamps are ticks, since the device is running!?
I think so. It's called "relative Timestamp" and KNX devices in general do not have actual time. 

From your packets the timestamp has 7343 tics per second. Seems close to the 9600baud of knx bus. As a guess the value might be incremented with bus clock.

**Comment by p3root** [comment]
@timowi what do you thing we should use in the knxd impl? I don't think that this timestamp is relevant at all...

**Comment by timowi** [comment]
I have created a new branch with this:
https://github.com/Makki1/knxd/compare/fixes-core/cemi-busmonitor-package

**Comment by timowi** [comment]
@p3root Your branch is not mergable the way you work. It's better to start new branches for different changes. 

You have a lot of whitespace changes in your commits. This makes it difficult to trace what was changed.

**Comment by p3root** [comment]
What about auto-indent all files? It becomes much better readable..
idk how you guys are working, but I started with vi (it's cool, but needs a lot more time) but now I'm using the QtCreator with the automake plugin.

**Comment by Makki1** [comment]
On idents, just my 2 cents, I have a very clear opinion:
no tabs, only spaces are allowed (I will have to add a "CodingStyleGuideline.md" maybe)

**Comment by p3root** [comment]
I use spaces to indent the code. But I'm on you, a coding style guideline is very useful.

**Pull request closed without merging**
