### PR TITLE
NCN5120 Support + EIBnetServer/IP Name as console param

### PR DESCRIPTION
**Pull request by p3root**
Added support for the NCN5120 knx transreceiver (Baud 38400 8BIT Mode)

Make it possible to give the EIBnetServer/IP name as console parameter (the name thats shown in the ETS interfaces)

### CODE REVIEW

**Comment by timowi** [comment]
nice.

but some points:

1. you reinsert removed code in configure.ac

2. This is C++, please use String (or const String) instead of 'char *'

3. Why an extra \0 in option default? 

4. You default to knxd if '-n' is given without a parameter. But in this case an error message should be printed.

**Comment by Makki1** [comment]
Good to see with more than 2 eyes :) I'd have missed two points..

**Comment by p3root** [comment]
i removed the string only in the eibnetserver.cpp class, in the argument struct of knxd.cpp are some char* used anyway...

**Comment by timowi** [comment]
yes there are a lot of 'char *'. But all new added variables and parameters should be C++ Strings.

One more point: never use strcpy. Please change to strncpy.

**Comment by Makki1** [comment]
i've merged it for now (I'm no "git-pro"), Patrik please address the discussed points and make a new pull-request as required

**Comment by RichiH** [comment]
@Makki1 it's usually better to not merge until the PR is in good shape. @timowi could simply update this PR again and again, or create new ones, until everyone is happy.

**Comment by Makki1** [comment]
@RichiH: got that! I'm not very experienced with github, working on a heavy rename-action (EIBnet -> KNXnet/IP) so I wanted to proceed as fast as possible and avoid source-clashes..

**Comment by timowi** [comment]
It's better to keep changes in branches for a while. It's no good idea to just merge branches.

We should talk about how changes go to master. It's no plan if everyone just commit his changes. I would like to review all changes which go to the core components (daemon, clientlib). I have seen many bugs introduced in "simple changes".

@Makki1 please commit your renaming to an branch for review. And please keep apart renaming and code changes. Something like "renaming" must be renaming only. Same goes for adding documentation.

**Comment by Makki1** [comment]
@timowi : the last thing I want is breaking things. So - with limited git know-how - I'll try to put that (rename) separate.
Backward-compatible in API and parameters is the goal.
But it has to be done and it is the right time is now (we cannot change it afterwards!), EIB is simply outdated for 8-10 years because its named KNX :)

**Comment by timowi** [comment]
> But it has to be done and it is the right time is now (we cannot change it afterwards!)
It's not the point that I do not want the changes. Because to change we are here.

I just want a strict development process at least for the core components. Important for this is to commit and discuss small changes. I know it's difficult to controll the impulse "to change what needs to be done anyway". It's a problem with discipline: You just want to refactor the code and then you see something you want to fix... This leads to complex and not review-able commits. So the important thing is to keep changes straight and simple. Otherwise it's just random hacking... It's just to easy to duplicate some state, missing a locking...

**Comment by RichiH** [comment]
@Makki1:

To create the branch:

    git checkout -B feature/rename_knxnet
    git push -u origin feature/rename_knxnet:feature/rename_knxnet

Afterwards, just

    git push origin feature/rename_knxnet


Unless you are _sure_ you don't have changes in master which you could push by accident, specifying the branch you are pushing to will help guard against mistakes. Don't worry, things will become clearer over time.

Also, `#git` on `irc.freenode.net` in case you have questions (and are OK with being told to rtfm)

**Comment by RichiH** [comment]
PS: After creating your new branch, you can

    git checkout master
    git reset --hard 55fb4ddfa2ca2d29f4067000a1efe52f6d1fb5d3
    git pull

That's overkill, but it should be safe and always give you a clean place to start new branches from.

And if you _really_ mess up, just remember to `cp -ax` the whole thing away and ask; mistakes are usually reasonably easy to find afterwards.

**Comment by Makki1** [comment]
Thanks! This is fully Off-topic, but one question: is there some place to test/learn like working on github but without being too public (just less embarrassing if one makes mistakes)?

**Comment by RichiH** [comment]
I would say `#git` and `#github` on freenode would be good places to start. Hanging out in there, asking when in doubt, _and reading the docs they point you to_ will get you up to speed in no time.

There are several online tutorials, but I never really used them so no idea how good they are.

And, while it's easier said than done, just ignore the "embarassing" bits. Create a test repo and break it in a myriad ways. Or create a knxd-crap repo and play with that. Doing many different things in ever-so-slightly different ways is key to understanding git.

**Pull request merged**
