### PR TITLE
 Define a list of duplicates to prevent author/email filtering on commits

### PR DESCRIPTION
**Pull request by mjoe**

### CODE REVIEW

**Comment by mjoe** [comment]
@Makki1, what's wrong with it?

**Comment by RichiH** [comment]
@mjoe Please see `.mailmap` and use that, instead. Sorry for not writing this earlier. I thought I did, but obviously I did not...

@Makki1 Please do _not_ merge.

**Comment by mjoe** [comment]
Therefore you should clean up AUTHORS and the scripting around to prevent confusions

**Comment by RichiH** [comment]
@mjoe I just fixed it. Please see 3c3e0b16ebc421c5e87b0298e6bd58bec44b7c03

If you have suggestions as to how to improve the wording in the scripts and output to make the workflow more clear, please let me know.

**Comment by Makki1** [comment]
Well, to be honest I still havent understood the benefit of using a script and a mechanism noone understands - instead of a just a simple Text file named AUTHORS (?)
Text-files are a good thing, every human understands..

**Comment by RichiH** [comment]
There is a simple text file called AUTHORS.

The script is simply a mechanism to make sure no one is missed by looking at the Git history. Updating the file by hand works just as well.

**Comment by Makki1** [comment]
OK, thanks. I didnt get that like this so far.. But still: if i'd change my Email to the right one now, the next commit will have a duplicate instead of just the Text 😀

**Comment by RichiH** [comment]
What's your correct email address?

**Pull request closed without merging**
