### PR TITLE
Created a common base for tpuartserial and ncn5120

### PR DESCRIPTION
**Pull request by p3root**
As discussed with @Makki1: I have created a shared base for tpuartserial and ncn5120 communication.

### CODE REVIEW

**Comment by timowi** [comment]
I am against merging this change now. This should be reviewed completely. It is to easy to introduce bugs in these changes.

Adding a new backand unproblematic. But I would not change exisitng (tpuart) backend without being sure.

**Comment by Makki1** [comment]
Agreed, we have to test this with at least six eyes. Timo, can you make a branch ?

**Comment by RichiH** [comment]
https://github.com/Makki1/knxd/tree/feature/merge_tpuart

**Comment by RichiH** [comment]
I am closing this for now; @p3root feel free to commit further against this branch.

Disclaimer: I can do the merges, but I can't really judge the code. But as long as it's a feature branch, nothing bad should happen anyway.

**Comment by timowi** [comment]
> Disclaimer: I can do the merges, but I can't really judge the code. But as long as it's a feature branch, nothing bad should happen anyway.

This is **not** a feature branch. This is a refactoring of two backends. One of the most sensible parts of knxd. 

If should be merged only if we are it actually is only refactoring. Unfortunately in large changes it's difficult to see if behavior changed. Even the most experienced programmers introduce bugs in these stepe from time to time.

It is easier to review if it's done in small comprehensible steps.

**Comment by RichiH** [comment]
No matter what you call it, it's a feature branch now ;)

I don't have an opinion on the refactoring itself; I am merely trying to help @Makki1 until he's firm enough with Git.

As to regressions: it would be best if we had some sort of test setup where changes could be applied, the tests run, and ensured that everything works as expected. I fear that's somewhat down the road, though...

**Comment by timowi** [comment]
> As to regressions: it would be best if we had some sort of test setup where changes could be applied, the tests run, and ensured that everything works as expected. I fear that's somewhat down the road, though...

yes, would be nice... Unfortunately it would not help here. It's near impossible to get good test coverage: Hardware involved with many possible states, different code path, multiple threads with locking -> Missing initialisation, changed states, wrong locking could be fine during testing but fail under certain timing in reality. That's why the daemon code is more important than the clients. These can be tested easily.

**Pull request closed without merging**
