### PR TITLE
Travis CI build state on main README file and a small fix for OS X

### PR DESCRIPTION
**Pull request by mjoe**
Signed-off-by: Joerg Mattiello <dev@mjoe.org>

### CODE REVIEW

**Comment by mjoe** [comment]
@Makki1 maybe you should recreate or re-enable your Travis project to see CI on master branch

**Comment by mjoe** [comment]
bump, what's up?

**Comment by RichiH** [comment]
Merged. We should get actual CI for this to make sure, though ;)

**Comment by mjoe** [comment]
Ok, so someone just needs to enable Makki1/knxd at Travis, then everything should just work. thanks

**Comment by RichiH** [comment]
What does that mean, precisely?

Richard

Sent by mobile; excuse my brevity.

**Comment by mjoe** [comment]
As soon as you allow travis to access your own github account (will be part of the first login procedure at travis), it will see all your repos (1-to-1 mapping). Then you just need to enable ci on the desired repo. Like i did, see https://travis-ci.org/mjoe/knxd. But i linked @Makki1 travis location on the main read file, so therefore it makes sense that he will enable travis too. Optionally, we link an other location on the main readme.

**Comment by RichiH** [comment]
@Makki1 : I tried this with https://github.com/RichiH/vcsh and it's
trivial, especially as `.travis.yml` exist, already. It should take you
less than 10 minutes, start to finish.


Richard

**Comment by RichiH** [comment]
PS: @mjoe : As a temporary workaround, I can point to your build
status. That means you need to keep all branches in sync, though.

**Comment by RichiH** [comment]
PPS: How can I point to branch-specific build info? Bad feature
branches should not show master as broken.

**Comment by mjoe** [comment]
You can link my travis location, branches will be in sync. build of branches can be defined in the travis spec file, see http://docs.travis-ci.com/user/build-configuration/#Specify-branches-to-build
not sure about the global build stat if just a branch will fail. We can check that quickly.

**Comment by RichiH** [comment]
@mjoe: I added yours for now

@Makki1 : Please let me know once you have a Travis CI account & enabled
knxd building

**Comment by Makki1** [comment]
I have just one small problem: not to know whats exactly happening here ! Something (App, I hate APP) wants full access to the repo and all personal data..

I have no problem giving *real* humans write-access without much discussion, but I have a problem with an unknown app where nobody knows who controls it..

**Comment by Makki1** [comment]
I've authorized it for now, but as soon as the first sight of strange things happen, I'll revert this..

**Comment by RichiH** [comment]
It's read-only access to the repo.

Personal data: to an extent, yes.

**Comment by mjoe** [comment]
@Makki1 if you feel uncomfortable with it, we can stay at my travis integration. Best would be if we move knxd to the group location at github and then at travis too. Then we do not need any personal account for that anymore.

**Comment by Makki1** [comment]
I've already created an org for knxd but avoided the move so far - just to avoid confusion.. As said, for now, I granted the rights.

**Comment by RichiH** [comment]
Switched back to @Makki1 's Travis.

**Comment by mjoe** [comment]
@Makki1 I don't if know any confusion about a project move will be different if we will do it later. Sometimes it may be better to clean up first to keep a setup simpel.
You still need to enable knxd at travis to get CI started.

**Pull request closed without merging**
