### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by vapourismo**
This would allow you to have continuous integration using Travis CI, as seen [here](https://travis-ci.org/vapourismo/knxd).
I highly recommend reading up on [Travis CI](https://travis-ci.org).

### CODE REVIEW

**Comment by Makki1** [comment]
Sorry, you have to explain that: it looks very platform-specific/dependant.
This make sense, but is more in scope of packaging i.e. /contrib?

**Comment by vapourismo** [comment]
It is impossible to put this into a place other than the root directory, due to the way Travis CI works.

Essentially what this does is give a detailed explaination to the Travis CI workers on how to build this package. Everytime somebody pushes to the repository or submits a pull request, Travis CI will notice that and try to build the package using the instructions delivered within the `.travis.yml`. Travis also notes when a build fails and will message you. It may also be used to do automated unit testing.

As said before I highly suggest you read a little about it on their [website](https://travis-ci.org/). It is a nice feature to have but definately not a must.

**Comment by Makki1** [comment]
OK, I dont see any reason to not merge this one file. (Anybody else?)
But be careful with pthsem, this is very likely to change in future..

**Comment by vapourismo** [comment]
I am glad you plan to disconnect `pthsem` from knxd.

**Pull request merged**
